import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import style from "styles/Home.module.css";
import styles from "styles/Landing.module.css";
import TelpIcon from "../../public/icons/telp-icon.png";
import Lock from "../../public/icons/lock-icon.png";
import Download from "../../public/icons/download-icon.png";
import Windows from "../../public/IMG/windows-logo.png";
import DropBox from "../../public/IMG/dropbox-logo.png";
import Hm from "../../public/IMG/hm-logo.png";
import Air from "../../public/IMG/air-logo.png";
import Canon from "../../public/IMG/canon-logo.png";
import Dell from "../../public/IMG/dell-logo.png";
import LayoutImg from "../../public/IMG/layout.png";
import ArrowLeft from "../../public/icons/arrow-left.png";
import ArrowRight from "../../public/icons/arrow-right.png";
import ProfImg from "../../public/IMG/profil.png";
import Link from "next/link";

export default function Home() {
  const { token, pin } = useSelector((state) => state.auth);
  const router = useRouter();
  useEffect(() => {
    if (pin && token) {
      router.push("/dashboard");
    }
  }, [pin]);
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>LukiPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>
      {/* <Navbar /> */}
      <header className={styles.headerBg}>
        <section className={styles.navBanner}>
          <div className={styles.fazzPay}>Fazzpay</div>
          <div className={styles.wrapperButton}>
            <Link href="/login">
              <div className={styles.btnLogin}>Login</div>
            </Link>
            <Link href="/signup">
              <div className={styles.btnSignUp}>Sign Up</div>
            </Link>
          </div>
        </section>
        <section className={styles.mainBanner}>
          <div className={styles.mainBannerTitle}>
            Awesome App For Saving Time.
          </div>
          <div className={styles.mainBannerBody}>
            We bring you a mobile app for banking problems that oftenly wasting
            much of your times.
          </div>
          <div className={styles.mainBannerFooter}>Try It Free</div>
        </section>
      </header>
      <main className={styles.containerContent}>
        <section className={styles.wrapperFeature}>
          <section className={styles.featureContent}>
            <div className={styles.featureContentTitle}>
              <div className={styles.why}>Why</div> Choose FazzPay?
            </div>
            <div className={styles.featureContentBody}>
              We have some great features from the application and it’s totally
              free to use by all users around the world.
            </div>
          </section>
          <section className={styles.featureContentFooter}>
            <div className={styles.wrapperFeatureContentFooter}>
              <div className={styles.featureContentFooterTitle}>
                <Image src={TelpIcon} alt="TelpIcon" />
              </div>
              <div className={styles.featureContentFooterBody}>
                24/7 Support
              </div>
              <div className={styles.featureContentFooterFooter}>
                We have 24/7 contact support so you can contact us whenever you
                want and we will respond it.
              </div>
            </div>
            <div className={styles.wrapperFeatureContentFooterLock}>
              <div className={styles.featureContentFooterTitle}>
                <Image src={Lock} alt="LockIcon" />
              </div>
              <div className={styles.featureContentFooterBody}>
                Data Privacy
              </div>
              <div className={styles.featureContentFooterFooter}>
                We make sure your data is safe in our database and we will
                encrypt any data you submitted to us.
              </div>
            </div>
            <div className={styles.wrapperFeatureContentFooter}>
              <div className={styles.featureContentFooterTitle}>
                <Image src={Download} alt="DownloadIcon" />
              </div>
              <div className={styles.featureContentFooterBody}>
                Easy Download
              </div>
              <div className={styles.featureContentFooterFooter}>
                Zwallet is 100% totally free to use it’s now available on Google
                Play Store and App Store.
              </div>
            </div>
          </section>
        </section>
        <section className={styles.wrapperMainLogo}>
          <Image src={Windows} alt="logo"></Image>
          <Image src={DropBox} alt="logo"></Image>
          <Image src={Hm} alt="logo"></Image>
          <Image src={Air} alt="logo"></Image>
          <Image src={Canon} alt="logo"></Image>
          <Image src={Dell} alt="logo"></Image>
        </section>
        <section className={styles.wrapperPrice}>
          <div className={styles.priceTitle}>Rp. 390.736.500</div>
          <div className={styles.priceBody}>
            <div className={styles.why}>Money </div>has Been Transfered.
          </div>
          <div className={styles.priceFooter}>
            That amount of money has been transfered from all users. We still
            counting and going strong!
          </div>
        </section>
        <section className={styles.wrapperFeatureTwo}>
          <aside className={styles.featureTwoImage}>
            <Image src={LayoutImg} alt="layoutImg"></Image>
          </aside>
          <aside className={styles.featureTwoContent}>
            <div className={styles.featureTwoContentTitle}>
              All The <div className={styles.why}>Great</div> FazzPay Features.
            </div>
            <div className={styles.wrapperFeatureContentBody}>
              <div className={styles.featureTwoContentHeader}>
                <div className={styles.why}>1.</div>Small Fee
              </div>
              <div className={styles.featureTwoContentBody}>
                We only charge 5% of every success transaction done in FazzPay
                app.
              </div>
            </div>
            <div className={styles.wrapperFeatureContentBody}>
              <div className={styles.featureTwoContentHeader}>
                <div className={styles.why}>2.</div>Data Secured
              </div>
              <div className={styles.featureTwoContentBody}>
                All your data is secured properly in our system and it’s
                encrypted.
              </div>
            </div>
            <div className={styles.wrapperFeatureContentBody}>
              <div className={styles.featureTwoContentHeader}>
                <div className={styles.why}>3.</div>User Friendly
              </div>
              <div className={styles.featureTwoContentBody}>
                FazzPay come up with modern and sleek design and not
                complicated.
              </div>
            </div>
          </aside>
        </section>
        <section className={styles.wrapperUser}>
          <div className={styles.userHeader}>
            <div className={styles.userTitle}>
              What Users are <div className={styles.why}>Saying.</div>
            </div>
            <div className={styles.userBody}>
              We have some great features from the application and it’s totally
              free to use by all users around the world.
            </div>
            <div className={styles.wrapperCard}>
              <div className={styles.arrowIcon}>
                <Image src={ArrowLeft} alt="arrowIcon"></Image>
              </div>
              <div className={styles.card}>
                <div className={styles.cardImg}>
                  <Image src={ProfImg} alt="profilImage"></Image>
                </div>
                <div className={styles.cardBody}>
                  <div className={styles.username}>Alex Hansinburg</div>
                  <div className={styles.role}>Designer</div>
                </div>
                <div className={styles.cardFooter}>
                  “This is the most outstanding app that I’ve ever try in my
                  live, this app is such an amazing masterpiece and it’s
                  suitable for you who is bussy with their bussiness and must
                  transfer money to another person aut there. Just try this app
                  and see the power!”
                </div>
              </div>
              <div className={styles.arrowIcon}>
                <Image src={ArrowRight} alt="arrowIcon"></Image>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className={style.footer}>
        <h3>Fazzpay</h3>
        <p className={style.footerinfo}>
          Simplify financial needs and saving much time in banking needs with
          one single app.
        </p>
        <div className={style.bottom}>
          <p>2020 LukiPay. All right reserved.</p>
          <p>
            <span>+62 5637 8882 9901</span> <span>contact@lukipay.com</span>
          </p>
        </div>
      </footer>
    </>
  );
}
